### ISSUE TITLE
MY BEAUTIFUL PHOTO CLASS#6

### ISSUE THREAD

**Issue by akadarAkku** [HackYourFutureBelgium/class-6#11]
![20190819_122439](https://user-images.githubusercontent.com/44436763/64990918-185ca500-d8d1-11e9-8a0d-c41775efdb61.jpg)

**Comment by KevinTss** [comment]
Yeah! Good pic Ibrahim, Enjoy your meal!

**Comment by akadarAkku** [comment]
Thanks You nkow we loooooooooooooooove foood
