### ISSUE TITLE
ilhan: databases, week 1 project

### ISSUE THREAD

**Issue by ikoral** [HackYourFutureBelgium/class-6#123]
### Databases Week 1 Project
* [databases-week1-project repository](https://github.com/ikoral/databases-projects/tree/master/week-1)

### Homeworks
- [x]  [Build you own ER diagram](https://github.com/ikoral/databases-projects/blob/master/week-1/ilhan-week01-homework01.pdf)
- [x]  [Create your database-library diagram](https://github.com/ikoral/databases-projects/blob/master/week-1/ilhan-week01-homework02-library.pdf)
- [x]  [Create your database-library query](https://github.com/ikoral/databases-projects/blob/master/week-1/library.sql)
- [x]  [Write queries to retrieve data from world db that answers questions](https://github.com/ikoral/databases-projects/blob/master/week-1/queries_for_world.sql)

### Homeworks Optional
- [x]  [Write queries answers  additional questions](https://github.com/ikoral/databases-projects/blob/master/week-1/queries_for_world.sql)
- [x]  [Homework From HYF GitHub Page week-1](https://github.com/ikoral/databases-projects/blob/master/week-1/queries_for_cars.sql)
- [x]  [Hackerrank Sql Practice](https://www.hackerrank.com/ikoral)
* Try to connect your node.js to mysql(ongoing)

**Comment by bromeroo** [comment]
Well done!
