### ISSUE TITLE
Akader-database-week 2

### ISSUE THREAD

**Issue by akadarAkku** [HackYourFutureBelgium/class-6#130]
**Akader-database-week 2  project**  

- [x]  [Exercise 1: Build Musicians ER diagram](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/week2erdiagram.pdf) 
- [X]  [WORLD-Slide-Homework](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/solution-silde.sql)
- [x]  [Exercise imdb.sql](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/imdb.sql)
- [x]  [Modify Travel Agency ERD ](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/TRAVEL-AGENCY%20ER%20DIAGRAM%20MODIFIED%20.pdf)

**Homework Optional**
- [x]  [ERD based on the imdb database](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/ERD%20based%20on%20the%20imdb%20database%20.pdf)

 
[My Dtabase Repo week 2](https://github.com/akadarAkku/databases/blob/master/week-2-homework/submissions/ERD%20based%20on%20the%20imdb%20database%20.pdf)

**Comment by bromeroo** [comment]
You did a super work :)

Thank you
