### ISSUE TITLE
Ufuk -databases-week-2

### ISSUE THREAD

**Issue by u-uysal** [HackYourFutureBelgium/class-6#132]
- [x]  [Exercise 1: world.sql](https://github.com/u-uysal/databases-week-2/blob/master/world_exercises.sql) 
- [x]  [Exercise 2: imdb.sql](https://github.com/u-uysal/databases-week-2/blob/master/imdb_exercises.sql) 
- [x]  [Exercise 3: Modify ERD Travel Agency](https://github.com/u-uysal/databases-week-2/blob/master/Basic%20Database%20ER%20Diagram%20(Ufuk%20Uysal-Travel%20Agency).pdf)

**Comment by bromeroo** [comment]
Reviewed Exercise 1, 2 and 3
