### ISSUE TITLE
ilhan: databases, week 2 project

### ISSUE THREAD

**Issue by ikoral** [HackYourFutureBelgium/class-6#137]
### Databases Week 2 Project
* [databases-week2-project repository](https://github.com/ikoral/databases-projects/blob/master/week-2/Homeworks-week2.md)
* [databases-week2-project-live-page](https://ikoral.github.io/databases-projects/)
### Homeworks
- [x]  [Exercise World](https://github.com/ikoral/databases-projects/blob/master/week-2/week02-exercise-world.sql)
- [x]  [Exercise IMDB](https://github.com/ikoral/databases-projects/blob/master/week-2/week02-exercise-imdb.sql)
- [x]  [Modify travel agency ERD](https://github.com/ikoral/databases-projects/blob/master/week-2/ilhan-week02-homework03-travel-agency-ERD.pdf)
- [x]  [Create travel agency Database](https://github.com/ikoral/databases-projects/blob/master/week-2/travelAgency.sql)

### What I am stuck on.

**Comment by bromeroo** [comment]
Great work again :) 

Thank you
