### ISSUE TITLE
Ufuk js3 week 1 project

### ISSUE THREAD

**Issue by u-uysal** [HackYourFutureBelgium/class-6#61]
### Week 1 Project Exercises
- [x]  [change-text](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/1-change-text.html)
- [x]  [change-link](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/2-chage-link.html)
- [x]  [uptade-list](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/3-update-list.html)
- [x]  [add-a-link](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/4-add-a-link.html)
- [x]  [add-a-header](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/5-add-a-header.html)
- [x]  [fix-the-list](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/6-fix-the-list.html)
- [x]  [start-from-nothing](https://u-uysal.github.io/javascript-3/dom-manipulation/exercises/7-start-from-nothing.html)

* GitHub pages
- [x]  [version 1](https://github.com/u-uysal/practical-javascript/tree/master/version-1)
- [x]  [version 2](https://github.com/u-uysal/practical-javascript/tree/master/version-2)
- [x]  [version 3](https://github.com/u-uysal/practical-javascript/tree/master/version-3)
- [x]  [version 4](https://github.com/u-uysal/practical-javascript/tree/master/version-4)
- [x]  [version 5](https://github.com/u-uysal/practical-javascript/tree/master/version-5)
- [x]  [version 6](https://github.com/u-uysal/practical-javascript/tree/master/version-6)
- [x]  [version 7](https://github.com/u-uysal/practical-javascript/tree/master/version-7)
- [x]  [version 8](https://github.com/u-uysal/practical-javascript/tree/master/version-8)
- [x]  [version 9](https://github.com/u-uysal/practical-javascript/tree/master/version-9)
- [x]  [version 10](https://github.com/u-uysal/practical-javascript/tree/master/version-10/index.html)

### JS3 Repository and Week-1 Project Live Page
* [JS 3 repository](https://github.com/u-uysal/javascript-3)
* [JS 3 live website](https://u-uysal.github.io/practical-javascript/)

**Comment by Toinne** [comment]
### Feedback

👍 👍 👍 Great work.
Good branching.
As you seem to have the hang of it be sure to continue with version 11.

A small remark:

- Formatting here is a bit all over the place here. Be sure to keep a consistent indentation throughout your file. I show a trick in the review section of class to make things easier for you.
https://github.com/u-uysal/practical-javascript/blob/d105fef2671c43e68b32dc1cacdcc79ede7e1e58/version-8/script.js#L60-L70
