### ISSUE TITLE
JS3-W2 Project.js

### ISSUE THREAD

**Issue by u-uysal** [HackYourFutureBelgium/class-6#83]
### Week 2 Project
* [exploring-github-api repository](https://github.com/u-uysal/exploring-github-api)
### Week 2 Project Exercises
 GitHub pages
- [x]  [section 1](https://github.com/u-uysal/exploring-github-api/tree/master/section-1)
- [x]  [section 2](https://github.com/u-uysal/exploring-github-api/tree/master/section-2)
- [x]  [section 3](https://github.com/u-uysal/exploring-github-api/tree/master/section-3)
- [x]  [section 4](https://github.com/u-uysal/exploring-github-api/tree/master/section-4)
- [x]  [section 5](https://github.com/u-uysal/exploring-github-api/tree/master/section-5)
- [x]  [section 6](https://github.com/u-uysal/exploring-github-api/tree/master/section-6)

**Comment by Toinne** [comment]
GREAT !

Be sure to revoke your token as it is like a password.
https://github.com/settings/tokens
